version: "3.8"

services:
  mysql-server:
    image: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=1234
    ports:
      - "33062:3306"
  
  myredis:
    image: redis
    ports:
      - "6380:6380"

  cassandra-node-0:
    image: cassandra
    environment:
      - CASSANDRA_SEEDS=cassandra-node-0
      - CASSANDRA_CLUSTER_NAME=MyCluster
      - CASSANDRA_ENDPOINT_SNITCH=GossipingPropertyFileSnitch
      - CASSANDRA_DC=dc1
    ports:
      - "7003:7003"  # 노드간 클러스터 내부 통신
      - "7001:7001"  # 노드간 보안 통신에 사용
      - "9042:9042"  # CQL 클라이언트와 통신
    healthcheck:
      test: [ "CMD-SHELL", "[ $$(nodetool statusgossip) = running ]" ]
      interval: 30s
      timeout: 10s
      retries: 5